### ISSUE TITLE
Couldn't run in web browser .

### ISSUE THREAD

**Issue by uewolf25** [howdy39/gas-clasp-starter#96]
## display error
Hi, I'm a university student. I love 'clasp' and 'gas-clasp-starter' .

I cloned this repository .
I could run this sample project before February .
Recently, command: `npm run deploy` and `clasp open` go very well, but couldn't run in web browser . (See the image below, plz)  
![error_global](https://user-images.githubusercontent.com/30000985/76335030-43332d80-6337-11ea-9f4b-19273875227a.png)  
This means we can't use [your sentences](https://github.com/howdy39/gas-clasp-starter/blob/master/src/index.ts#L4) `declare var global: any;` ???
How can I use and run successfully again ?
Because of being introduced 'V8' ???

## Development version
- Node version (`node -v`): v13.10.1
- Version (`clasp -v`): 2.3.0
- OS (Mac/Linux/Windows): Mac

**Comment by howdy39** [comment]
Hi @uewolf25 

`gas-clasp-startar` builds two files.

``` 
└─ dist/appsscript.json
└─ dist/bundle.js
```

sample
![image](https://user-images.githubusercontent.com/6329532/76528081-97fbb300-64b3-11ea-8941-aac619850ab6.png)


But the File name in which the error occurred is `src/index`.
Looks like the build is failing.

---

Also, is the `rootDir` of the clasp.json file set to dist?

```
{
  "scriptId": "<your_script_id>",
  "rootDir": "dist" <- Check it
}
```

**Comment by uewolf25** [comment]
Thanks for your replay, @howdy39  .

I missed adding `--rootDir` option when I create my project .
So, clasp.json is not set `"rootDir": "dist"` ...
___
I could run my project in my own way .
Too much appreciation !!

thx
